server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/projectmanagement?userSSL=false&serverTimezone=Asia/Shanghai
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml

logging:
  level:
    root: info
    com.example.projectmanagement.mapper: debug